name: preflight-checkers 
on:
  pull_request_target:
    branches: [ $default-branch ]
  push:
    branches: [ $default-branch ]
  workflow_dispatch:

permissions:
 contents: read
 security-events: write

jobs:
  checker:
    uses: qualcomm/qcom-actions/.github/workflows/multi-checker.yml@v1.1.3
    with:
        repolinter: true # default: true
        semgrep: true # default: true
        copyright-license-detector: true # default: true
        pr-check-emails: true # default: true

    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}